### ISSUE TITLE
The exclude options are wrong way round. Remove ANDs

### ISSUE THREAD

**Issue by forty-rachel** [FoodStandardsAgency/lit-fetch#33]
https://github.com/FoodStandardsAgency/lit-fetch/blob/b58af2232ccf4757b86742dcd867af9067584b85/R/mod_filter.R#L37

If I want to exclude any title with X or Y in then I do an internal OR and it doesn't remove them. Simplify this don't need AND just have list of ORs or one box

**Comment by helen-food** [comment]
linked to #36 

just have a single box separating terms with OR
