### ISSUE TITLE
only display reasons for possible errors if there is an error in the search, display in red

### ISSUE THREAD

**Issue by forty-rachel** [FoodStandardsAgency/lit-fetch#68]
Currently tool always states:
If the above search returned an error please check that you have closed all your brackets. Some special characters (i.e. &) may also cause errors.

We have a check for uneven brackets bracket_match_check so could give this a specific error message and take out of generic one

**Comment by forty-rachel** [comment]
works for mismatched brackets, doesn't work for "cake & gluten" - I think previously there was a warning, now it just closes - may worth going through special characters and seeing what the tool dislikes!

**Comment by forty-rachel** [comment]
doesn't like when " are not closed

**Comment by forty-rachel** [comment]
Interesting - cake and 'gluten intolerance' returns one more result than cake and "gluten intolerance" - it looks like this is caused by Scopus

**Comment by forty-rachel** [comment]
annoying one - don't think we can have the quote marks error for ' as you can have "it's alive"

**Comment by xavier-gilbert** [comment]
single quote removed
