### ISSUE TITLE
publication date format (date or char) different across searches

### ISSUE THREAD

**Issue by xavier-gilbert** [FoodStandardsAgency/lit-fetch#74]
pubmed, scopus, springer have pub date as char
ebsco has pub date as date

=> harmonize

**Comment by xavier-gilbert** [comment]
Ebsco -> to char

**Comment by forty-rachel** [comment]
lowercase dates are being annoying

**Comment by forty-rachel** [comment]
Can deal with these if we care enough! May98

**Comment by xavier-gilbert** [comment]
Moved to its own issue (this one was related to data type `char` `date`).
