### ISSUE TITLE
Error : Join columns must be present in data.

### ISSUE THREAD

**Issue by xavier-gilbert** [FoodStandardsAgency/lit-fetch#77]
```
[31mx[39m Problem with `doi`.
```

Query: "United Kingdom" AND (Biomonitor* OR Breastmilk OR "Multi-biomarker study" OR "Multi-biomarker study" OR Mycotoxin)
Since: 2020-02-02

**Comment by forty-rachel** [comment]
@xavier-gilbert what am I checking here?

**Comment by xavier-gilbert** [comment]
@forty-rachel the DOI was not appearing anymore, cause of the anti-join, there was a mistake, normally fixed now but essentially checking that all columns are there at the end.

**Comment by forty-rachel** [comment]
was this for any source in particular or just when you have more than one source?

**Comment by xavier-gilbert** [comment]
It was for Ebsco and when there are more than one source selected (so Ebsco + additional source).

**Comment by forty-rachel** [comment]
sory noticed this is no longer in the QA col, should I still look at it or is it still broken?
