### ISSUE TITLE
discrepancy searches (exclude ebsco)

### ISSUE THREAD

**Issue by xavier-gilbert** [FoodStandardsAgency/lit-fetch#79]
Differences in volumes between results app in prod and app in dev.
`searchterm <- "gluten AND intolerance"`

**Comment by forty-rachel** [comment]
is this one done? I have tested against old tool without ebsco

**Comment by xavier-gilbert** [comment]
I think they are not really comparable anymore anyway cause I fixed a couple errors and filters and dates on the other ones. What was the result of the test?

**Comment by forty-rachel** [comment]
I ran them at the stage that everything had been refactored and it was all good - will do again now to capture changes

**Comment by xavier-gilbert** [comment]
Oh yes now I remember the results you sent. My apologies.
